name: Build Mod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle properly
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
          ls -lh gradle.zip
          unzip gradle.zip

      - name: Build project
        run: |
          ./gradle-8.7/bin/gradle build --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: VulkanShaderLoader-JAR
          path: build/libs/*.jar
